# Intermediate Workshop 1: numpy, loops and *if statements*

## 1.1 Numpy

> Numpy's main object is the multidimensional array, known as an ndarray. It can also be referred as an array.  
Indeed, numpy.array is just a convenience function to create an ndarray.  
So,  an ndarray should always be constructed using *array*, *zeros*, or *empty* as per numpy's documentation.

In [3]:
import numpy as np

# instantiating an ndarray using array
arr = np.array([[1,2,3],[10,11,12]])
arr, type(arr)

(array([[ 1,  2,  3],
        [10, 11, 12]]), numpy.ndarray)

In [4]:
# instantiating an ndarray using zeros
zeros_arr = np.zeros((3,2)) # the input is a tuple to determine the desired shape
zeros_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [5]:
# instantiating an ndarray using empty
empty_arr = np.empty((3,2))
empty_arr

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

> The main attributes of an ndarray are  
* ndim: the number of axes (dimensions) of the array
* shape: the dimension of the array (for an n*m array, the dimension is the tuple (n,m))
* size: number of elements in the array (n times m)
* dtype: all elements in an numpy have the same type (dtype)

In [6]:
{'ndim': arr.ndim, 'shape': arr.shape, 'size': arr.shape, 'dtype': arr.dtype}

{'ndim': 2, 'shape': (2, 3), 'size': (2, 3), 'dtype': dtype('int32')}

> We can use arithmetic operations on arrays, these operations are applied _elementwise_.

In [7]:
arr2 = np.arange(6).reshape(2,3) # the arange function just creates a array with
  # elements from 0 to size
print(arr)
print(arr2)
arr + arr2

[[ 1  2  3]
 [10 11 12]]
[[0 1 2]
 [3 4 5]]


array([[ 1,  3,  5],
       [13, 15, 17]])

In [8]:
arr * arr2

array([[ 0,  2,  6],
       [30, 44, 60]])

> There exists a bunch of unary function that works on arrays. For instance, the square root function, the exponential function and so on.

In [9]:
print(np.sqrt(arr))
np.sqrt(arr)

[[1.         1.41421356 1.73205081]
 [3.16227766 3.31662479 3.46410162]]


array([[1.        , 1.41421356, 1.73205081],
       [3.16227766, 3.31662479, 3.46410162]])

> In the previous workshop, we saw how indexing and slicing can be used on lists and strings. Now, we can use these same concepts on arrays.

In [10]:
print(arr)
print(arr[1:, 1:])
print(arr[0, 0])
print(arr[-1, -1])

[[ 1  2  3]
 [10 11 12]]
[[11 12]]
1
12


> For arrays, there is a new character _..._ that can be particularly useful when indexing arrays with lots of dimensions.  
$x[1,2...] = x[1, 2, :, :, :]$

In [11]:
arr[..., 0] # select only the first "column"

array([ 1, 10])

> We can stack arrays on top of eachother to extend our defined arrays. We can use the *vstack* to stack data vertically or *htstack* to stack data horizontally.

In [12]:
new_row = np.array([1000, 2000, 3000])
np.vstack((arr, new_row)) # inputs have the shape of a tuple

array([[   1,    2,    3],
       [  10,   11,   12],
       [1000, 2000, 3000]])

In [13]:
new_column = np.array([999, 888])
new_column = new_column.reshape(2,1)
print(new_column)
np.hstack((new_column, arr))

[[999]
 [888]]


array([[999,   1,   2,   3],
       [888,  10,  11,  12]])

> Something you must always keep in mind in numpy, and often in Python is that you access variable by reference, and not by value. In other words, when I re-assign an array, it is the same one re-assigned twice.

In [14]:
new_arr = arr
print(arr is new_arr)
arr[0,0] = 999999
new_arr

True


array([[999999,      2,      3],
       [    10,     11,     12]])

> If I want to actually copy an array to modify one variable independently of the other, you can use the *copy* function.


In [15]:
new_arr = arr.copy()
print(arr is new_arr)
arr[0,0] = 22222
new_arr

False


array([[999999,      2,      3],
       [    10,     11,     12]])

> Let's create a bigger array with the *arange* function.

In [16]:
big_arr = np.arange(100).reshape(10, 10)
big_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### Exercise 1

> Retrieve the last row of the *big_arr*.

In [17]:
def exercise1(arr):
  x = None
  return x

assert (exercise1(big_arr) == np.array([90, 91, 92, 93, 94, 95, 96, 97, 98, 99])).all()

AssertionError: 

## 1.2 *If statements*

> As the goal of this workshop is to make you very comfortable with looping in Python, the second building block necessary for this goal is to understand control flow tools and control statements. We will start with the *if statement*.

In [18]:
condition = True # boolean variable set to true

if condition == True: 
  print('this statement runs')

condition = False

if condition == True:
  print('this statement does not')

this statement runs


> In the previous cell, a lot of new keywords and concepts were introduced, let's describe them
```
if condition == True
````
The $==$ is a comparison operator which compares the value to its right to the value to its left. If the two elements are equal, then the whole expression evaluates to true and can be understood as
```
if True == True  
if True: # True == True reduces to True
```
Now, the *if statement*, being $True$, executes the piece of code after the colon. In our case,
```
print('this statement runs')
```
executes.  
In the second case, 
```
if condition == True
```
evaluates to 
```
if False == True
```
and since $False \neq True$, then the expression evaluates to $False$ just like
```
if False
```
and so the block of code delimated by this *if statement* does not execute.  
To summarize, *if statements* only execute their code if their condition is $true$.
```
if condition:
  their code
 ```
 Where their code is indented more than the if line.



> Beside the equality comparison operator $(==)$ seen in the previous cell, there exists a lot more logic operators in python. The opposite of the equality comparison operator is the *not equal* operator $(!=)$. There exists also the *greater* and *greater or equal* operators $(>=, >)$, the *less than* and *less or equal* operators $(<=, <)$, and the negation operator (not).

In [19]:
condition = True
small_number = 5
huge_number = 100000

if not condition:
  print('will not print')
  
if condition != False:
  print('will print')
  
if small_number > huge_number:
  print('will not print')
  
if small_number < huge_number:
  print('will print')
  
if huge_number >= small_number:
  print('will print')

will print
will print
will print


> The equal sign with a boolean value is optional
```
if condition == True:
  print('hi')
```
is exactly the same statement as
```
if condition:
  print('hi')
```
and
```
if condition == False:
  print('hi')
```
is exactly the same statement as 
```
if not condition:
  print('hi')
```

In [20]:
condition = False
if not condition:
  print('not False == True, so I print')

if condition:
  print('will not print')

not False == True, so I print


> We can mix conditions together for more flexibility in logical expressions such as  *if statements*. We have the $and$ and the $or$ statements

| Condition 1 | Condition 2 | or    | and   |
|-------------|-------------|-------|-------|
| False       | False       | False | False |
| False       | True        | True  | False |
| True        | False       | True  | False |
| True        | True        | True  | True  |

We can interpret this table with the following code
``` 
if False and True:
  print('will not print')
  
if False or True:
  print('will print')
  
```

In [21]:
if False or False:
  print('this does not print')

if True and True:
  print('this will print')
  
 

this will print


> The examples seen  in the previous cells all used boolean values or numbers . However, we can create more complex conditions involving strings and functions.

In [22]:
name = 'Jack O'

if name == 'Jack O':
  print('this will print')

if len(name) == 6:
  print('this will print')
  
if name == 'Jack O' and len(name) == 6:
  print('this will print')

this will print
this will print
this will print


### Exercise 2

> Make sure that either number1 or number2 lie between their respective thresholds

In [23]:
def exercise2(number1, low_threshold1, high_threshold1,
              number2, low_threshold2, high_threshold2):
  pass

assert exercise2(10, 15, 20, 12, 10, 11) == False

assert exercise2(8, 6, 9, 10, 11, 22) == True


AssertionError: 

## 1.3 Loops

> Loops are very important in any good programming languages, and Python is no exception. They are often used to iterate over some lists, arrays or iterable data structure, or to repeat a task multiple times. Python features two main types of loops: the *for loop* and the *while loop*.

In [24]:
for element in big_arr:
  print("current element: {}".format(element))

current element: [0 1 2 3 4 5 6 7 8 9]
current element: [10 11 12 13 14 15 16 17 18 19]
current element: [20 21 22 23 24 25 26 27 28 29]
current element: [30 31 32 33 34 35 36 37 38 39]
current element: [40 41 42 43 44 45 46 47 48 49]
current element: [50 51 52 53 54 55 56 57 58 59]
current element: [60 61 62 63 64 65 66 67 68 69]
current element: [70 71 72 73 74 75 76 77 78 79]
current element: [80 81 82 83 84 85 86 87 88 89]
current element: [90 91 92 93 94 95 96 97 98 99]


> Let's understand the previous statement. 
```
for element in big_arr:
```
since *big_arr* is a multidimensional array (a 2 dimension array in our case), we iterate over the rows. Everything is taken care of under the hood such that the loop stops automatically.  We can appreciate the simplicity of Python when we compare to other programming languages, such as C.
```
int[][] big_arr = new int[10][10];
for (int i = 0; i < 10; i++){
  printf("current element:");
  for (int j = 0; j < 10; j++)}
    printf("%f", big_arr[i][j]);  
  }
  printf("\n");
}
```

We might want the index for numerous purposes such as printing the current iteration. We use the *enumerate* method to do so. 

In [25]:
for index, element in enumerate(big_arr):
  print('current index: {}, current element: {}'.format(index, element))

current index: 0, current element: [0 1 2 3 4 5 6 7 8 9]
current index: 1, current element: [10 11 12 13 14 15 16 17 18 19]
current index: 2, current element: [20 21 22 23 24 25 26 27 28 29]
current index: 3, current element: [30 31 32 33 34 35 36 37 38 39]
current index: 4, current element: [40 41 42 43 44 45 46 47 48 49]
current index: 5, current element: [50 51 52 53 54 55 56 57 58 59]
current index: 6, current element: [60 61 62 63 64 65 66 67 68 69]
current index: 7, current element: [70 71 72 73 74 75 76 77 78 79]
current index: 8, current element: [80 81 82 83 84 85 86 87 88 89]
current index: 9, current element: [90 91 92 93 94 95 96 97 98 99]


> Notice that the loop starts at index 0 and not 1.  
We can pile up loops on top of each other. The first loop is called the _outer_ loop while the second loop is calle dthe _inner_ loop.

In [26]:
for i, row in enumerate(big_arr): # outer loop
  for j, element in enumerate(row): # inner loop
    if i * big_arr.shape[0] + j < 20: # I print only the first 20 elements
      print(element) 

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


### Exercise 3

> Compute the average value of the $x$ array.

In [27]:
x = np.random.randn(100)

def exercise3(arr):
  _sum = 0
  return _sum


assert '{:3f}'.format(exercise3(x)) == '{:3f}'.format(np.average(x))

AssertionError: 

> There exists another way of dealing with *for loops* in Python which is named list comprehensions. The basic syntax is 
```
[ expression for item in list if condition ]
```
notice the two bracked surrounding the line, as well as the few keywords.  
* for: the variable name following the for is an individual element coming from the list which can be accessed in the expression.
* in: the variable following the in keyword represents where we are looping on.
* if:  the if keyword as well as its condition that follows it are optional.

In [37]:
random_values = np.random.randn(12)
print(np.average(random_values))
top_x_values = [el for el in random_values if el > np.average(random_values)]
top_x_values

-0.019922292112282376


[0.6414412389252723,
 0.2099006295640668,
 0.300886351097635,
 0.05492078564340846,
 0.8319457661383078,
 1.008280837606465]

In [40]:
# creating a simple 2d list
twodim_list = [[] for whatever in range(5)]
twodim_list

[[], [], [], [], []]

> There is another type of loop which is the *while* loop that has a different structure. The *while* loop uses the same structure as the *if statement* seen previously. It executes until its condition evaluates to $False$.
```
while condition:
  expression
```
The expression runs only if the condition evaluates to $True$.

In [41]:
i = 0
while i < 5:
  print('i value: {}'.format(i))
  i = i + 1 # alternatively i += 1

i value: 0
i value: 1
i value: 2
i value: 3
i value: 4


> Let's wrap our conversation about loops with the *range*  function
```
range(start, stop, step)
```
All three parameters are optional, by default $start$ is 0, $stop$ is nothing and $step$ is 1. In other words, it's an $\infty $ range. If we give one parameter to the range function, it's the stop value.
```
range(10)
```
So if we use the following line in our code, we will be able to loop 10 times.

In [42]:
for x in range(5):
  print(x)

0
1
2
3
4


> Let's use the notion we saw today to preprocess some dataset. The dataset we will look at is the World Hapiness Report 2019. We will use pandas DataFrame to manipulate the data.

In [43]:
import io
import pandas as pd
whr = pd.read_csv('world-happiness-report-2019.csv')
whr.loc[30:60]

Country (region)  Ladder  SD of Ladder  Positive affect  \
30               Panama      31           121              7.0   
31               Brazil      32           116             69.0   
32              Uruguay      33            88             10.0   
33            Singapore      34             5             38.0   
34          El Salvador      35           112             23.0   
35                Italy      36            31             99.0   
36              Bahrain      37            83             39.0   
37             Slovakia      38            39             53.0   
38  Trinidad and Tobago      39            89             14.0   
39               Poland      40            28             76.0   
40           Uzbekistan      41            99             19.0   
41            Lithuania      42            55            138.0   
42             Colombia      43           120             30.0   
43             Slovenia      44            54            114.0   
44            Nicaragua      45           133             31.0   
45               Kosovo      46           107             71.0   
46            Argentina      47            97             28.0   
47              Romania      48            75             80.0   
48               Cyprus      49            95             60.0   
49              Ecuador      50           113             11.0   
50               Kuwait      51            98             89.0   
51             Thailand      52            81             20.0   
52               Latvia      53            30            119.0   
53          South Korea      54            57            101.0   
54              Estonia      55            32             50.0   
55              Jamaica      56           102             51.0   
56            Mauritius      57            94             55.0   
57                Japan      58            43             73.0   
58             Honduras      59           151             13.0   
59           Kazakhstan      60            40             81.0   
60              Bolivia      61            71             70.0   

    Negative affect  Social support  Freedom  Corruption  Generosity  \
30             48.0            41.0     32.0       104.0        88.0   
31            105.0            43.0     84.0        71.0       108.0   
32             76.0            35.0     30.0        33.0        80.0   
33              2.0            36.0     20.0         1.0        21.0   
34             84.0            83.0     74.0        85.0       134.0   
35            123.0            23.0    132.0       128.0        48.0   
36             83.0            59.0     24.0         NaN        23.0   
37             47.0            21.0    108.0       142.0        70.0   
38             52.0            29.0     51.0       141.0        41.0   
39             33.0            44.0     52.0       108.0        77.0   
40             15.0            11.0      1.0        18.0        29.0   
41             41.0            17.0    122.0       113.0       124.0   
42             88.0            52.0     56.0       124.0       111.0   
43             71.0            14.0     13.0        97.0        54.0   
44            125.0            66.0     70.0        43.0        71.0   
45              7.0            85.0     50.0       144.0        31.0   
46             93.0            46.0     54.0       109.0       123.0   
47             62.0            86.0     57.0       146.0       102.0   
48             99.0            90.0     81.0       115.0        39.0   
49            113.0            71.0     42.0        68.0        95.0   
50             97.0            69.0     47.0         NaN        42.0   
51             35.0            53.0     18.0       131.0        10.0   
52             38.0            34.0    126.0        92.0       105.0   
53             45.0            91.0    144.0       100.0        40.0   
54              6.0            12.0     45.0        30.0        83.0   
55             51.0   

> When reading the World Happiness Dataset, we notice that some values are $NaN$, which stands for not a number. We will loop on this dataframe to replace the not a number to the number of rows in our dataset. Naively, we will replace $NaN$ value with the number of rows in this dataset.

In [44]:

number_of_rows = whr.shape[0]
number_of_columns = whr.shape[1]


for i in range(number_of_rows):
  for j in range(1, number_of_columns):
    if np.isnan(whr.iloc[i, j]):
      print('i: {}, j: {}'.format(i,j))
      whr.iloc[i, j] = number_of_rows


i: 20, j: 7
i: 24, j: 9
i: 24, j: 10
i: 27, j: 7
i: 28, j: 3
i: 28, j: 4
i: 28, j: 5
i: 28, j: 6
i: 28, j: 7
i: 28, j: 8
i: 36, j: 7
i: 45, j: 10
i: 50, j: 7
i: 63, j: 9
i: 63, j: 10
i: 75, j: 10
i: 86, j: 7
i: 92, j: 7
i: 100, j: 7
i: 109, j: 10
i: 111, j: 9
i: 134, j: 10
i: 148, j: 9


In [45]:
whr.loc[30:60]

Country (region)  Ladder  SD of Ladder  Positive affect  \
30               Panama      31           121              7.0   
31               Brazil      32           116             69.0   
32              Uruguay      33            88             10.0   
33            Singapore      34             5             38.0   
34          El Salvador      35           112             23.0   
35                Italy      36            31             99.0   
36              Bahrain      37            83             39.0   
37             Slovakia      38            39             53.0   
38  Trinidad and Tobago      39            89             14.0   
39               Poland      40            28             76.0   
40           Uzbekistan      41            99             19.0   
41            Lithuania      42            55            138.0   
42             Colombia      43           120             30.0   
43             Slovenia      44            54            114.0   
44            Nicaragua      45           133             31.0   
45               Kosovo      46           107             71.0   
46            Argentina      47            97             28.0   
47              Romania      48            75             80.0   
48               Cyprus      49            95             60.0   
49              Ecuador      50           113             11.0   
50               Kuwait      51            98             89.0   
51             Thailand      52            81             20.0   
52               Latvia      53            30            119.0   
53          South Korea      54            57            101.0   
54              Estonia      55            32             50.0   
55              Jamaica      56           102             51.0   
56            Mauritius      57            94             55.0   
57                Japan      58            43             73.0   
58             Honduras      59           151             13.0   
59           Kazakhstan      60            40             81.0   
60              Bolivia      61            71             70.0   

    Negative affect  Social support  Freedom  Corruption  Generosity  \
30             48.0            41.0     32.0       104.0        88.0   
31            105.0            43.0     84.0        71.0       108.0   
32             76.0            35.0     30.0        33.0        80.0   
33              2.0            36.0     20.0         1.0        21.0   
34             84.0            83.0     74.0        85.0       134.0   
35            123.0            23.0    132.0       128.0        48.0   
36             83.0            59.0     24.0       156.0        23.0   
37             47.0            21.0    108.0       142.0        70.0   
38             52.0            29.0     51.0       141.0        41.0   
39             33.0            44.0     52.0       108.0        77.0   
40             15.0            11.0      1.0        18.0        29.0   
41             41.0            17.0    122.0       113.0       124.0   
42             88.0            52.0     56.0       124.0       111.0   
43             71.0            14.0     13.0        97.0        54.0   
44            125.0            66.0     70.0        43.0        71.0   
45              7.0            85.0     50.0       144.0        31.0   
46             93.0            46.0     54.0       109.0       123.0   
47             62.0            86.0     57.0       146.0       102.0   
48             99.0            90.0     81.0       115.0        39.0   
49            113.0            71.0     42.0        68.0        95.0   
50             97.0            69.0     47.0       156.0        42.0   
51             35.0            53.0     18.0       131.0        10.0   
52             38.0            34.0    126.0        92.0       105.0   
53             45.0            91.0    144.0       100.0        40.0   
54              6.0            12.0     45.0        30.0        83.0   
55             51.0   

### Exercise 4

> Retrieve the element having the smallest value from the row corresponding to poland.

In [46]:
def exercise4(row):
  smallest_value = 100000
  return smallest_value

row = whr.iloc[39, 1:]
assert exercise4(row) == 28

AssertionError: 